"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['timer_app.py']
DATA_FILES = ['025.icns',"save.ini", ('', ['Pokemon_Smile_Pokemon']), ('', ['Pokemon_Smile_Envs'])]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
